import { useMediaQuery } from "react-responsive";
import { MenuItem } from "../utils/menuItems";
import { FabDrawer } from "mdrl";
import { Hero } from "../components/Hero";
import type { NextPage } from "next";
import Head from "next/head";
<footer className={styles.footer}>Created By Andrew Patrick Miller</footer>;
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const isBigScreen = useMediaQuery({ query: "(min-width: 700px)" });
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Hero />
        <p
          style={{
            marginTop: isBigScreen ? -120 : -120,
            fontSize: isBigScreen ? 24 : 14,
            fontWeight: isBigScreen ? 400 : 600,
            textAlign: "left",
            width: "100%",
            padding: isBigScreen ? "12%" : "20%",
            lineHeight: 3,
            letterSpacing: 5,
          }}
        >
          Hello dear vistor, Thanks for being here.
          <br />
          {!isBigScreen && <br />}
          Please use the hamburger menu to navigate. Thanks!
          <br />
          -Andrew
        </p>
      </main>
    </div>
  );
};

export default Home;
