import { MenuItem } from "../utils/menuItems";
import { FabDrawer } from "mdrl";
import { Hero } from "../components/Hero";
import type { NextPage } from "next";
import Head from "next/head";
<footer className={styles.footer}>Created By Andrew Patrick Miller</footer>;
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Hero />
        <p
          style={{
            marginTop: -20,
            fontSize: 14,
            textAlign: "left",
            width: "100%",
            padding: "20%",
            lineHeight: 3,
            letterSpacing: 5,
          }}
        >
          Hello dear vistor, Thanks for being here. Please use the hamburger
          menu in the lower right to open the navigation drawer and browse my
          portfolio. Thanks!
          <br />
          -Andrew
        </p>
      </main>
    </div>
  );
};

export default Home;
