import Head from "next/head";
import { PageHeader } from "../components/PageHeader";
import { CertificateCard } from "../components/CertifcateCard";
import { ProjectCard } from "../components/ProjectCard";
export default function AboutAndrew(props) {
  const listStyle = { fontSize: 20, marginLeft: 30 };
  return (
    <>
      <Head>
        <title>Certificates</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header style={{ display: "flex", justifyContent: "Center" }}>
        <PageHeader headerText="Certificates and Such" />
      </header>
      <main
        style={{
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          justifyContent: "flex-start",
        }}
      >
        <CertificateCard
          title="Bachelors of Science Chemistry Biochemistry"
          certificateUrl="bs-chem.jpg"
          certificateOrgUrl="https://www.uaf.edu/chem"
          certificateOrg={"UAF Chemistry Department"}
          description="This is the degree I received from the University of Alaska Fairbanks for completing the chemistry curriculum with a biochemistry emphasis."
        />
        <CertificateCard
          title="OpenJS Service Developer Certification"
          certificateUrl="jsnad.jpg"
          certificateOrgUrl="https://training.linuxfoundation.org/certification/jsnad/"
          certificateOrg="Linux Foundation JSNAD"
          description="This is the certificate I received from the Linux OpenJS Foundation  partnership for completing the JavaScript Node Application Developer live programming exam."
        />

        <CertificateCard
          title="OpenJS Service Developer Certification"
          certificateUrl="jsnsd.jpg"
          certificateOrgUrl="https://training.linuxfoundation.org/certification/jsnsd/"
          certificateOrg="Linux Foundation JSNSD"
          description="This is the certificate I received from the Linux and OpenJS Foundation for completing the JavaScript Node Services Developer live programming exam."
        />
      </main>
    </>
  );
}
