import Head from "next/head";
import { PageHeader } from "../components/PageHeader";
import { useMediaQuery } from "react-responsive";
import { ProjectCard } from "../components/ProjectCard";
export default function AboutAndrew(props) {
  const listStyle = { fontSize: 20, marginLeft: 30 };
  const isBigScreen = useMediaQuery({ query: "(min-width: 700px)" });
  return (
    <>
      <Head>
        <title>Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        style={{
          marginTop: "5%",
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          justifyContent: "flex-start",
        }}
      >
        <PageHeader headerText="NestJS CRUD App" />
        <ProjectCard
          emoji="🐈"
          projectTitle="NestJS Crud App"
          description="This is a nestjs crud app, the basic functionality was built in a couple days, and I will continue to build it out as I wish. There is a react front end being built with next.js in the repo."
          projectUrl="https://github.com/Milldrew/nestjs"
        />
        <ProjectCard
          emoji="💼"
          projectTitle="Portfolio Site"
          description="This website was built using React.js and Next.js"
          projectUrl="https://github.com/Milldrew/portfolio"
        />
        <ProjectCard
          emoji="📚"
          projectTitle="Milldrew's React Library"
          description="This is a react component library that I use to leverage 'component driven development'. If I create a component that will be useful across projects I add it to this package and retrieve it with yarn when needed."
          projectUrl={"https://github.com/Milldrew/milldrews-library"}
        />
        <ProjectCard
          emoji="🗳"
          projectTitle="Idaho Election Book"
          projectUrl="https://github.com/Milldrew/rn-client"
          description="This is a React Native Mobile app I am building. It uses the Idaho voter's registration data to validate that a user is a registered voter before allowing them to partake in surveys and polls"
        />
        <ProjectCard
          projectUrl="https://github.com/Milldrew/todo-parent-repo"
          emoji="✅"
          projectTitle="Federated Todo List"
          description="This project was contrived to practice using apollo federation to build micro services, federation consists of a gateway service and graphql subgraph services. I decided to use git submodules which was not a good choice. I would have been better off using yarn workspaces. I need to refactor this project then  finish building the frontend. "
        />
      </main>
    </>
  );
}
